id: PA84074BA
initial_creation_type: ocr
source_metadata:
  volumes:
    14ecfd082fee47848feb00402b2a1cc8:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
